import { Metadata } from "next";

import { Layout } from "@/enums";
import { ForgotPassword } from "@/page-content";
import { withLayoutPage } from "@/hoc";

export const metadata: Metadata = {
    title: 'Forgot password',
    description: 'Generated by create next app',
}

const ForgotPasswordPage = () => <ForgotPassword />

export default withLayoutPage({ PageComponent: ForgotPasswordPage, layoutType: Layout.Auth });