import { Metadata } from "next";

import { Layout } from "@/enums";
import { SignIn } from "@/page-content";
import { withLayoutPage } from "@/hoc";

export const metadata: Metadata = {
    title: 'Sign in',
    description: 'Generated by create next app',
}
  
const SignInPage = () => <SignIn />

export default withLayoutPage({ PageComponent: SignInPage, layoutType: Layout.Auth });