import { PropsWithChildren } from 'react'
import { Metadata } from 'next'

import { AppProviders } from '@/components';
import { envUtil } from '@/utils';

import './globals.css'


const appName = envUtil.getEnv().appName;

export const metadata: Metadata = {
  title: {
    template: `${appName} | %s`,
    default: `${appName}`,
  },
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: PropsWithChildren<{}>) => {
  return (
    <html lang="en">
      <body>
        <main>
          <AppProviders>{children}</AppProviders>
        </main>
      </body>
    </html>
  )
}

export default RootLayout;