import { Metadata } from "next";

import { Layout } from "@/enums";
import { SignUp } from "@/page-content";
import { withLayoutPage } from "@/hoc";

export const metadata: Metadata = {
    title: 'Sign up',
    description: 'Generated by create next app',
}

const SignUpPage = () => <SignUp />

export default withLayoutPage({ PageComponent: SignUpPage, layoutType: Layout.Auth });